.PHONY: load-test
load-test:
	$(MAKE) -C ./load load-test

.PHONY: integration-bootstrap
integration-bootstrap:
	$(MAKE) -C ./integration bootstrap

.PHONY: integration-test
integration-test:
	$(MAKE) -C ./integration test
