stages:
  - lint
  - unit-test

lint_code:
  stage: lint
  image: golangci/golangci-lint:v1.49
  script:
    - golangci-lint run ./backend/...

unit_tests:
  stage: unit-test
  image: golang:1.19.1
  script:
    - make test
