version: '3.9'

services:
  postgres_db:
    extends:
      file: ../backend/docker/common-services.yml
      service: postgres_db
    env_file: ../backend/docker/database/.dev.env
    volumes:
      - ../backend/database/data:/data/dbcp/
    ports:
      - 5432:5432
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    extends:
      file: ../backend/docker/common-services.yml
      service: migration
    env_file: ../backend/docker/migration/.dev.env
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: on-failure:3

  tarantool-db:
    extends:
      file: ../backend/docker/common-services.yml
      service: tarantool-db
    ports:
      - 3301:3301
    env_file:
      - ../backend/docker/cache/.dev.env

  cube-dev:
    extends:
      file: ../backend/docker/common-services.yml
      service: cube
    image: cosmtrek/air
    working_dir: /tmp/project
    entrypoint: ["/go/bin/air", "-c", "cube/.air.toml"]
    env_file:
      - ../backend/docker/cube/.dev.env
    ports:
      - 10001:10001
    volumes:
      - ../backend/go.sum:/tmp/project/go.sum
      - ../backend/go.mod:/tmp/project/go.mod
      - ../backend/vendor/:/tmp/project/vendor
      - ../backend/pkg:/tmp/project/pkg
      - ../backend/cache:/tmp/project/cache
      - ../backend/config:/tmp/project/config
      - ../backend/database:/tmp/project/database
      - ../backend/cmd/cube:/tmp/project/cmd/cube
      - ../backend/cube:/tmp/project/cube
      - ../backend/cube/.air.toml:/tmp/project/cube/.air.toml
      - ../backend/cube/.dev.yml:/tmp/config.yml
      - ../backend/out/crypto:/tmp/crypto/
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: always
