// Code generated by mockery v2.15.0. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// NormalizerConfig is an autogenerated mock type for the NormalizerConfig type
type NormalizerConfig struct {
	mock.Mock
}

type mockConstructorTestingTNewNormalizerConfig interface {
	mock.TestingT
	Cleanup(func())
}

// NewNormalizerConfig creates a new instance of NormalizerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNormalizerConfig(t mockConstructorTestingTNewNormalizerConfig) *NormalizerConfig {
	mock := &NormalizerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
