// Code generated by mockery v2.11.0. DO NOT EDIT.

package mock

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// NormalizerConfig is an autogenerated mock type for the NormalizerConfig type
type NormalizerConfig struct {
	mock.Mock
}

// NewNormalizerConfig creates a new instance of NormalizerConfig. It also registers a cleanup function to assert the mocks expectations.
func NewNormalizerConfig(t testing.TB) *NormalizerConfig {
	mock := &NormalizerConfig{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
