global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cube
    metrics_path: /prometheus
    dns_sd_configs:
      - names: ['cube']
        type: 'A'
        port: 10001
